#!/usr/bin/env bash
if [ $1 == "event" ]; then
  jq '.homepage = "https://hacktj.org/2020"' package.json > tmp.$$.json && mv tmp.$$.json package.json
  sed 's|<Router>|<Router basepath="/2020">|' src/App.js | tee src/App.js
  sed 's|<base href="/" />|<base href="/2020" />|' public/index.html | tee public/index.html
  git remote set-url origin git@github.com:HackTJ/2020.git
elif [ $1 == "homepage" ]; then
  jq '.homepage = "https://hacktj.org"' package.json > tmp.$$.json && mv tmp.$$.json package.json
  sed 's|<Router basepath="/2020">|<Router>|' src/App.js | tee src/App.js
  sed 's|<base href="/2020" />|<base href="/" />|' public/index.html | tee public/index.html
  git remote set-url origin git@github.com:HackTJ/hacktj.github.io.git
else
  echo "Invalid argument"
  exit 128
fi
